default:
  target: dev
  outputs:
    dev:
      type: snowflake
      threads: 1
      client_session_keep_alive: false
      account: dummy
      user: dummy
      password: dummy
      role: dummy
      database: dummy
      schema: dummy
      warehouse: dummy
