# all commands by default will run on every commit, not every push
default_install_hook_types: [pre-commit]
default_stages: [pre-commit]

# some configs are only available after v2.18
minimum_pre_commit_version: '2.18'

repos:
        
  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v2.0.4
    hooks:
      - id: check-model-has-properties-file
      - id: check-script-has-no-table-name