name: dbt Checkpoint Hooks

on:
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit dbt-core dbt-snowflake
          pip install git+https://github.com/dbt-checkpoint/dbt-checkpoint.git

      - name: Set up dbt profiles.yml
        run: |
          mkdir -p ~/.dbt
          cp .github/dummy_profiles.yml ~/.dbt/profiles.yml

      - name: Install dbt packages
        run: dbt deps

      - name: Parse dbt project (no database connection)
        run: dbt parse

      - name: Get changed SQL files from PR base
        id: get_sql_files
        run: |
          base_sha="${{ github.event.pull_request.base.sha }}"
          head_sha="${GITHUB_SHA}"

          echo "Comparing base $base_sha to head $head_sha"

          files=$(git diff --name-only "$base_sha" "$head_sha" -- '*.sql')

          echo "sql_files<<EOF" >> $GITHUB_OUTPUT
          echo "$files" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT


      - name: Run dbt-checkpoint only on changed files
        id: run_checkpoint
        run: |
          read -r -a files <<< "${{ steps.get_sql_files.outputs.sql_files }}"
          if [ -z "${files[*]}" ]; then
            echo "No changed SQL files to check."
            exit 0
          fi

          echo "Checking: ${files[*]}"
          pre-commit run --files "${files[@]}" | tee checkpoint_output.txt

      - name: Add dbt-checkpoint summary to GitHub job summary
        if: always()
        run: |
          echo '### dbt-checkpoint Summary' >> $GITHUB_STEP_SUMMARY

          # Strip ANSI color codes
          sed -r "s:\x1B\[[0-9;]*[mK]::g" checkpoint_output.txt > clean_output.txt

          # Append pass/fail message
          if grep -q "Failed" clean_output.txt; then
            echo '⚠️ Some dbt-checkpoint checks failed. Please review the output below.' >> $GITHUB_STEP_SUMMARY
          else
            echo '✅ All dbt-checkpoint checks passed successfully!' >> $GITHUB_STEP_SUMMARY
          fi

          # Dump clean output
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat clean_output.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY


          